ARG BLALALA_BASE_IMAGE=python:3.11-slim
FROM ${BLALALA_BASE_IMAGE}

WORKDIR /app

COPY requirements.blalala.api.txt .
RUN pip install --no-cache-dir -r requirements.blalala.api.txt

COPY app ./app

COPY entrypoint.blalala.api.sh .
RUN chmod +x entrypoint.blalala.api.sh

EXPOSE 3000

CMD ["./entrypoint.blalala.api.sh"]